include: package:flutter_lints/flutter.yaml

# Additional lint rules for the project
linter:
  rules:
    # Enable additional rules
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_constructors_in_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    avoid_print: true
    avoid_unnecessary_containers: true
    avoid_web_libraries_in_flutter: true
    no_logic_in_create_state: true
    prefer_relative_imports: true
    sized_box_for_whitespace: true
    use_build_context_synchronously: true
    use_key_in_widget_constructors: true

# Analyzer settings
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore
