name: university_bus_tracker
description: A comprehensive Flutter application for tracking university buses with real-time GPS tracking, role-based authentication, and admin management features.
publish_to: 'none'

version: 1.0.0+1

homepage: https://github.com/YOUR_USERNAME/university-bus-tracker
repository: https://github.com/YOUR_USERNAME/university-bus-tracker
issue_tracker: https://github.com/YOUR_USERNAME/university-bus-tracker/issues
documentation: https://github.com/YOUR_USERNAME/university-bus-tracker/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.3.4
  
  # Maps - OpenLayers for web compatibility
  # mapbox_maps_flutter: ^1.0.0  # Removed - doesn't work well in Chrome
  
  # HTTP for API calls
  http: ^1.4.0
  
  # State Management
  provider: ^6.1.1
  
  # Navigation
  go_router: ^12.1.3
  
  # Location Services
  geolocator: ^10.1.0
  permission_handler: ^11.2.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  
  # Utils
  shared_preferences: ^2.2.2
  uuid: ^4.3.3
  intl: ^0.19.0
  
  # Icons
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Uncomment and add assets when needed
  # assets:
  #   - assets/images/
  #   - assets/icons/

  # Uncomment and add font files when needed
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
